Draft: Loop invariant detection.
oflatt/eggcc pull request #124
Opened 2023-10-27 19:10 UTC by clyben

Work in progress:
This PR adds loop_invariant.egg which detects the invariant parts inside a Theta node. 
An Operand into a Theta node is invariant if it goes through the Theta, where the i-th output is (Arg i).
The program creates a top-level demand on a Theta node and propagates the demand down to every subpart of the node until it meets the base case of constants or operands and records it. Then the program propagates up along with the previously made demands (on Body/Expr/Operand) while recording if that Body/Expr/Operand is constituted sorely by invariant parts.

Tests are work in progress...

2023-10-30 23:47 UTC, yihozhang commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +(relation is_inv_vo (Body Body VecOperand))
The second Body may not be necessary.

2023-10-30 23:47 UTC, yihozhang commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +(relation arg_inv_helper (VecOperand Body i64))
Describe what it(s every argument) does.

2023-10-30 23:47 UTC, yihozhang commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +		(< i (vec-length outputs))
mixed use of space and tab

2023-10-30 23:47 UTC, yihozhang commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +       (arg_inv theta i))
Leave a comment for why this is useful for efficiency

2023-10-30 23:47 UTC, yihozhang commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +(rule ((find_inv_vo	theta owner vo)) ((find_inv_vo_helper theta owner vo 0)))
tab

2023-10-30 23:47 UTC, yihozhang commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +(relation find_inv_vo_helper (VecOperand Body Body i64))
clarify what each column does

2023-11-02 02:28 UTC, clyben commented
I need to modify is_inv_body/expr/oprd from relation to function to 0/1 since in code motion I will also need to find if expr/body/.. are not invariant.

2023-11-03 22:15 UTC, oflatt requested changes
My main concern with this PR is that it doesn't include any tests- could you add small test, one negative and one positive case at least?

2023-11-03 22:15 UTC, oflatt commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +(relation arg_inv_helper (VecOperand Body i64))
Put a TODO here- I think can replace this with @rtjoa's idea of having a table with a range of integers

2023-11-03 22:15 UTC, oflatt commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +;; a theta is invariant in a context when all input are inv.
Is this rule just unsound then? If it is, we should not include it.

2023-11-03 22:20 UTC, clyben commented
@oflatt I think I accidentally removed the test in merging....

2023-11-07 22:50 UTC, oflatt requested changes
Small changes requested

2023-11-07 22:50 UTC, oflatt commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +;; an operand is moved when it's on the edge of invariant and variants
delete these

2023-11-07 22:50 UTC, oflatt commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +;; match on every binary op, see loop_invariants.rs
another commented out rule here

2023-11-07 22:50 UTC, oflatt commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +(relation is_inv_vo_helper (Body VecOperand i64))
need a comment- this proves everything up to an index is invariant?

2023-11-07 22:50 UTC, oflatt commented on src/rvsdg/egglog_optimizer/loop_invariant.egg
> +(rule ((= theta (Theta pred inputs outputs)))
Change this to also have a clause `(VecOperand-get outputs index)`

2023-11-07 22:50 UTC, oflatt commented on src/rvsdg/tests.rs
> +                                                                  (Node (PureOp (bmul (IntT) (Node (PureOp (bsub (IntT) (Arg 1)
bad indentation

2023-11-08 00:30 UTC, oflatt approved these changes
Great work!

2023-11-08 00:30 UTC, merged