PEGs in Rust
oflatt/eggcc pull request #27
Opened 2023-08-30 22:12 UTC by Alex-Fischman

This PR:
- Creates a Rust representation of PEGs (heavily inspired by the RVSDG encoding).
- Adds a method to convert Rust RVSDGs to Rust PEGs. (This was done so that there wouldn't be two different CFG -> Dataflow functions. However, it does mean that the PEGs are occasionally inefficient because RVSDG theta nodes are currently do-while/tail-controlled, so the translation requires unrolling the theta nodes an extra step.)
- Adds a method to simulate (interpret) a PEG.
- Adds a method to write a PEG out as a .dot file (although ordering of children isn't preserved so it''s slightly misleading).
- Adds some tests for the PEG conversion that mirror the RVSDG tests.

2023-08-31 18:03 UTC, oflatt requested changes
Overall awesome work, had a few comments.
I'm guessing this code will be quite fragile going forward but lets get there when we get there.

2023-08-31 18:03 UTC, oflatt commented on src/peg/mod.rs
> +    /// Does nothing (but useful for creating cycles).
Update comment to say that it's a layer of indirection for convenience. I guess we could do another pass to remove.

2023-08-31 19:47 UTC, Alex-Fischman commented on src/peg/simulate.rs
> +                        ValueOps::Add => Literal::Int(int(xs[0].clone()) + int(xs[1].clone())),
I looked at this and the bril interpreter is really not designed to execute a single function; it takes strings as arguments and produces stdout and stderr. What's annoying is that such a function does exist internally but it's private.

2023-08-31 20:31 UTC, oflatt approved these changes

2023-08-31 20:31 UTC, merged

2023-09-01 00:13 UTC, wilcoxjay commented on src/peg/simulate.rs
> +                        ValueOps::Add => Literal::Int(int(xs[0].clone()) + int(xs[1].clone())),
We should consider submitting a bril PR to expose this function.